services:
  mariadb:
    image: mariadb:latest
    container_name: fraud-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fraud_detection
      MYSQL_USER: fraud_user
      MYSQL_PASSWORD: fraud_pass
    ports:
      - "3306:3306"  # Changed from 3307:3306
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - fraud-network
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always

  quarkus-service:
    build:
      context: ./backendservices/quarkus-service
      dockerfile: Dockerfile
    container_name: quarkus-service
    environment:
      - JAVA_OPTS=-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mariadb://mariadb:3306/fraud_detection?allowPublicKeyRetrieval=true&useSSL=false
      - QUARKUS_DATASOURCE_USERNAME=fraud_user
      - QUARKUS_DATASOURCE_PASSWORD=fraud_pass
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
      - python-quarkus-service
    networks:
      - fraud-network
    restart: always

  python-quarkus-service:
    build:
      context: ./backendservices/python-quarkus-service
    container_name: python-quarkus-service
    ports:
      - "5005:5000"
    networks:
      - fraud-network
    restart: always

  frontend:
    build:
      context: ./frontendservices
    container_name: fraud-frontend
    ports:
      - "3000:3000"
    networks:
      - fraud-network

networks:
  fraud-network:
    driver: bridge

volumes:
  mariadb_data:

