version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: fraud-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fraud_detection
      MYSQL_USER: fraud_user
      MYSQL_PASSWORD: fraud_pass
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - fraud-network

  quarkus-service:
    build:
      context: ./backendservices/quarkus-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: quarkus-service
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mariadb://mariadb:3306/fraud_detection
      - QUARKUS_DATASOURCE_USERNAME=fraud_user
      - QUARKUS_DATASOURCE_PASSWORD=fraud_pass
      - QUARKUS_HTTP_CORS=true
      - QUARKUS_HTTP_CORS_ORIGINS=http://localhost:3000,http://frontend:3000
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - fraud-network

  python-quarkus-service:
    build:
      context: ./backendservices/python-quarkus-service
    container_name: python-quarkus-service
    ports:
      - "5005:5000"
    networks:
      - fraud-network

  python-service:
    build:
      context: ./backendservices/python-service
    container_name: python-service
    ports:
      - "8501:8501"
    networks:
      - fraud-network

  frontend:
    build:
      context: ./frontendservices
    container_name: fraud-frontend
    ports:
      - "3000:3000"
    networks:
      - fraud-network

networks:
  fraud-network:
    driver: bridge

volumes:
  mariadb_data:

